name: 'AEM AI Code Review'
description: 'Automated code review using AI for pull requests'
author: 'Farhan Nawaz <nawaz@adobe.com>'

inputs:
  gh-token:
    description: 'GitHub token for authentication'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  openai-endpoint:
    description: 'OpenAI API endpoint'
    required: true
  gh-app-id:
    description: 'GitHub App ID'
    required: true
  gh-installation-id:
    description: 'GitHub App Installation ID'
    required: true
  pull-request-number:
    description: 'Pull Request number to review'
    required: true

outputs:
  comments:
    description: 'Review Comments'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'code'
  color: 'blue'
