name: Test PR Review Action

on:
  pull_request:
    types: [opened, edited]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Match this with your package.json

      - name: Install dependencies
        run: npm install
        
      - name: Run PR Review Action
        uses: ./  # Path to your action
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_app_id: ${{ secrets.GH_APP_ID }}
          github_private_key: ${{ secrets.GH_PRIVATE_KEY }}
          github_installation_id: ${{ secrets.GH_INSTALLATION_ID }}